export const SearchResultSample = [
  {
    id: '1',
    name: 'Abrigos / Sueter Nike',
    subtitle: 'Sueter Nike',
    brand: 'Nike',
    category: 'Sueter',
    total: 28.00,
    stock: 100,
    rate: 4,
    desc: 'Quisque maximus scelerisque porttitor. In facilisis efficitur nibh, ut vestibulum lorem eleifend id.',
    images: ['product1.jpg','product1.jpg','product1.jpg'],
  },
  {
    id: '1',
    name: 'Abrigos / Sueter Nike',
    subtitle: 'Sueter Nike',
    brand: 'Nike',
    category: 'Sueter',
    total: 28.00,
    stock: 100,
    rate: 4,
    desc: 'Quisque maximus scelerisque porttitor. In facilisis efficitur nibh, ut vestibulum lorem eleifend id.',
    images: ['product1.jpg','product1.jpg','product1.jpg'],
  },
  {
    id: '1',
    name: 'Abrigos / Sueter Nike',
    subtitle: 'Sueter Nike',
    brand: 'Nike',
    category: 'Sueter',
    total: 28.00,
    stock: 100,
    rate: 4,
    desc: 'Quisque maximus scelerisque porttitor. In facilisis efficitur nibh, ut vestibulum lorem eleifend id.',
    images: ['product1.jpg','product1.jpg','product1.jpg'],
  },
  {
    id: '1',
    name: 'Abrigos / Sueter Nike',
    subtitle: 'Sueter Nike',
    brand: 'Nike',
    category: 'Sueter',
    total: 28.00,
    stock: 100,
    rate: 4,
    desc: 'Quisque maximus scelerisque porttitor. In facilisis efficitur nibh, ut vestibulum lorem eleifend id.',
    images: ['product1.jpg','product1.jpg','product1.jpg'],
  },
  {
    id: '1',
    name: 'Abrigos / Sueter Nike',
    subtitle: 'Sueter Nike',
    brand: 'Nike',
    category: 'Sueter',
    total: 28.00,
    stock: 100,
    rate: 4,
    desc: 'Quisque maximus scelerisque porttitor. In facilisis efficitur nibh, ut vestibulum lorem eleifend id.',
    images: ['product1.jpg','product1.jpg','product1.jpg'],
  },
  {
    id: '1',
    name: 'Abrigos / Sueter Nike',
    subtitle: 'Sueter Nike',
    brand: 'Nike',
    category: 'Sueter',
    total: 28.00,
    stock: 100,
    rate: 4,
    desc: 'Quisque maximus scelerisque porttitor. In facilisis efficitur nibh, ut vestibulum lorem eleifend id.',
    images: ['product1.jpg','product1.jpg','product1.jpg'],
  },
  {
    id: '1',
    name: 'Abrigos / Sueter Nike',
    subtitle: 'Sueter Nike',
    brand: 'Nike',
    category: 'Sueter',
    total: 28.00,
    stock: 100,
    rate: 4,
    desc: 'Quisque maximus scelerisque porttitor. In facilisis efficitur nibh, ut vestibulum lorem eleifend id.',
    images: ['product1.jpg','product1.jpg','product1.jpg'],
  },
  {
    id: '1',
    name: 'Abrigos / Sueter Nike',
    subtitle: 'Sueter Nike',
    brand: 'Nike',
    category: 'Sueter',
    total: 28.00,
    stock: 100,
    rate: 4,
    desc: 'Quisque maximus scelerisque porttitor. In facilisis efficitur nibh, ut vestibulum lorem eleifend id.',
    images: ['product1.jpg','product1.jpg','product1.jpg'],
  },
  {
    id: '1',
    name: 'Abrigos / Sueter Nike',
    subtitle: 'Sueter Nike',
    brand: 'Nike',
    category: 'Sueter',
    total: 28.00,
    stock: 100,
    rate: 4,
    desc: 'Quisque maximus scelerisque porttitor. In facilisis efficitur nibh, ut vestibulum lorem eleifend id.',
    images: ['product1.jpg','product1.jpg','product1.jpg'],
  },
]